### ISSUE TITLE
Inline parameters don't show when there is a space in the file path

### ISSUE THREAD

**Issue by CodePidgy** [RobertOstermann/vscode-inline-parameters#7]
I'm running Python 3.10.4 and tested this on a simple program:
```python
def test_func(msg: str, addon: str):
    print(msg + " " + addon)

test_func("Hello", "World")
```
However, no inline parameters are shown.
This is the output:
```
expression line: 2 | expression character: 4 | argument start line: 2 | argument start character: 10 | argument end line: 2 | argument end character: 27
NEW EXPRESSION
expression line: 4 | expression character: 0 | argument start line: 4 | argument start character: 10 | argument end line: 4 | argument end character: 17
expression line: 4 | expression character: 0 | argument start line: 4 | argument start character: 19 | argument end line: 4 | argument end character: 26
NEW EXPRESSION
```
So clearly it is running, but nothing is showing. Any ideas?

**Comment by RobertOstermann** [comment]
Hmm, that is interesting. I just tested with Python 3.10.4 on my machine and did not have any issues with the parameters showing.  

- Do you have the Python extension `ms-python.python` installed? You should be able to see some hover information if you have your mouse over the words `print` or `test_func`.
- Do you have this in your settings.json `"editor.inlayHints.enabled"` set to `on` or `true` (if not using latest VSCode version). If you are using the latest version I think that defaults to `on` so that is probably not it. 
- Have you tried typing in that file or switching to a different file and switching back? On initial startup the parameters might not get filled if the language server from the Python extension has not yet provided the hover values for my extension to read.

Let me know if any of those suggestions help. If not, I can try to look into it more or give you some tips to debug it and find the problem yourself.

**Comment by CodePidgy** [comment]
Okay, I figured it out. If the current working directory or current file has a space in the name then it won't work. A bit of an inconvenience, but at least I found the problem. Will this be fixed or must the user adapt to it?

**Comment by RobertOstermann** [comment]
Oh, makes sense. Thanks for figuring out the problem. I have just published version 1.1.5 that should fix the problem. You might still run into some issues if there are spaces in the Python path, but hopefully that is not the case. Let me know if this new version fixes your problem.

**Comment by CodePidgy** [comment]
Unfortunately it still doesn't work. For example, the directory "Testing" works, but "Testing Inline" doesn't.

**Comment by RobertOstermann** [comment]
Weird, it is working for me on a Windows machine. Are you on Windows, Mac, or Linux? The output channel _Inline Parameters Extended_ should give you a command that is run for that specific file. Can you copy that exact command and run it in the default shell and see if you get an error when running it? On Windows it should be using the Command Prompt shell in VSCode, not sure what it uses on Linux or Mac.

**Comment by cyrus123456** [comment]
go do not work
![image](https://user-images.githubusercontent.com/73327722/167448125-f6cf2611-ff18-41a9-b06e-59f086fb2767.png)

**Comment by CodePidgy** [comment]
@RobertOstermann, I see you updated it to have quotation marks around the file name, but not the folder name. This is the command:
`f:\Python\Testing Inline\.venv\Scripts\python.exe "c:\Users\aidan\.vscode\extensions\robertostermann.inline-parameters-extended-1.1.5/out/src/python/helpers/main.py" "f:/Python/Testing Inline/main.py"`

So it raises the error: `'f:\Python\Testing' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by RobertOstermann** [comment]
@Thermohalia I was seeing some weird problems when I tried adding quotes around that at first, but looking at it again I think that was just on my end. I have published version 1.1.6 that adds quotes around that initial command. Hopefully this fixes your issue.

**Comment by RobertOstermann** [comment]
@cyrus123456 Do you know if your problem is related to this issue of having spaces in the command?

**Comment by CodePidgy** [comment]
@RobertOstermann, it is now working properly. Thank so much for responding and fixing it so quickly and I'm just glad I could help.

**Comment by CodePidgy** [comment]
Okay, so it worked perfectly in my small testing arena, but now I have questions. Is this extension perhaps not ready for large programs? In my 400ish line program I can see that it is trying to work because if I open a separate file in the directory it works, but in the large one it doesn't? I ran the command that it gives in the output, and it works, but nothing is shown? If I put `print()` right at the end of the file, that works, but the rest of the methods and invocations don't.

**Comment by RobertOstermann** [comment]
Go and Python are both probably not well-optimized for large programs. I typically work in PHP and have optimized that to handle files of basically any size. However, a program that is less than 1,000 lines should not run into problems related to file size. I don't work much with Python and there are probably cases that I am not parsing the hover information correctly. Is the `print()` showing correctly if it is somewhere in the middle of the file? Or does it only work at the end of the file?

**Comment by CodePidgy** [comment]
It works in a class method as well as at the end of the file.

**Comment by RobertOstermann** [comment]
The extension uses basically a two-step process. First, it gets the AST and uses that to determine the places that function calls happen. That is what you see happening when running the command. Second, the extension uses the locations of those function calls and executes the hover provider, which is provided by the Python extension and is what you see when you hover your mouse over the function call. That hover provider information is parsed to determine the correct parameter name for each argument.

Given that the `print()` statement works inside a class method and at the end of the file, that means the AST is probably doing its job correctly, but if you wanted to be certain you could check the output of the command and ensure it is giving you the correct position for your function calls. Again, that is probably not necessary as it should be working correctly. 

This means that the issue is likely happening when I am attempting to parse the hover provider, which can be difficult to fix without an example of where it is failing when it should be working. Is it possible for you to narrow down a situation that is not working and provide an example, either through a pull request that updates the [example.py](https://github.com/RobertOstermann/vscode-inline-parameters/blob/master/test/example.py) file or in a comment here?

**Comment by CodePidgy** [comment]
![image](https://user-images.githubusercontent.com/33547278/167472603-699553fe-31fa-467b-8506-7a9168429590.png)
In the image above you can see that it is trying to do it. The one at `with open()` where it is telling me that file is one of the args popped up a few minutes ago. So it is working, it's just struggling.

**Comment by RobertOstermann** [comment]
@Thermohalia Ok, I have looked into this and I am definitely parsing it incorrectly. The python extension returns a different formatted output when the method is called on an object, such as `line.split()`. It will probably take a couple days, but I will get this fixed when I have some time.

**Comment by CodePidgy** [comment]
It's all good mate, I'm just glad to help. Keep me posted!

**Comment by RobertOstermann** [comment]
The issue seems to be an easier fix than I initially thought. I have put a fix out in version 1.1.8 that might fix your problems. I have not tested it thoroughly, but it should fix at least some of the issues. And I absolutely appreciate your help in finding these problems. Let me know if this version fixes works as you expect or if you are still seeing problems.

**Comment by CodePidgy** [comment]
It seems to be working in most if not all cases and is much faster. I don't really have time to test it extensively right now, but I will let you know if I find something.

**Comment by RobertOstermann** [comment]
Awesome, glad it is working better for you. I am going to close this issue as the original problem has been solved. If you run into any other problems while using this extension please create another issue.
